name: Dart

on:
  push:
    paths:
      - '.github/workflows/dart.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Dart SDK
        run: dart --version

      - name: Set up Dart environment
        uses: dart-lang/setup-dart@v2
        with:
          sdk: '3.1.3'  

      - name: Install dependencies
        run: flutter pub get

      - run: flutter doctor
      
      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: dart/screenshots/
